### ISSUE TITLE
BN and FN definitions are incorrect

### ISSUE THREAD

**Issue by Jake-Gillberg** [dckc/togl#2]
Wikipedia had it wrong. A name cannot be both free and bound in a process. This is confirmed in Meredith's rho-calc paper, and by Mike Stay in discord. Bound names are the names of a process that are not free.

Currently:
```
*picalc2> bn(New("x") (Sum[((Input "y" "a"), zero), ((Output "b" "a"), zero)]))
["x", "a"] : List String
*picalc2> fn(New("x") (Sum[((Input "y" "a"), zero), ((Output "b" "a"), zero)]))
["y", "b", "a"] : List String

```

**Comment by Jake-Gillberg** [comment]
It might be good to use the examples from the second Pi Calc lecture as test cases / if you think of any other good test cases, please notify me so that I can add them to the lecture.

https://github.com/RChain-Collaborative-Learning/PiCalculus/blob/master/lesson2.md#what-are-the-free-and-bound-names

**Comment by dckc** [comment]
I'm not sure I see the relevance of Meredith's rho-calc paper. picalc2.lidir follows Milner's tutorial. But the suggestion of test cases from lesson2 is a good one in any case.

**Comment by Jake-Gillberg** [comment]
RE: rho-calc paper. I don't believe there was intention to change the definition of free and bound names for the rho-calculus, and Milner's paper is unspecific as to if a name can be both free and bound (to my reading).
